export interface UKLocation {
  slug: string
  name: string
  region: string
  county?: string
  lat: number
  lon: number
  lastFrostDate: string        // e.g. "15 April"
  lastFrostMonth: number       // 0-indexed month
  lastFrostDay: number
  firstFrostDate: string       // autumn first frost
  frostFreeDays: number        // average per year
  averageMayLowC: number       // key for planting decisions
  description: string          // unique paragraph for SEO
  plantingAdvice: string       // location-specific advice
  microclimate?: string        // any notable local factors
}

export const ukLocations: UKLocation[] = [
  // === LONDON & SOUTH EAST ===
  {
    slug: 'london',
    name: 'London',
    region: 'London',
    lat: 51.5074, lon: -0.1278,
    lastFrostDate: '6 April', lastFrostMonth: 3, lastFrostDay: 6,
    firstFrostDate: '4 November',
    frostFreeDays: 212,
    averageMayLowC: 9,
    description: 'London benefits from the urban heat island effect, making it one of the warmest cities in the UK for gardeners. The dense urban fabric retains heat overnight, pushing last frost dates earlier than surrounding rural areas.',
    plantingAdvice: 'London gardeners can typically plant tomatoes and peppers outside from mid-May, around 2–3 weeks earlier than the national average. South-facing walls and sheltered courtyards can push this even earlier.',
    microclimate: 'Urban heat island adds ~2°C compared to rural Surrey'
  },
  {
    slug: 'brighton',
    name: 'Brighton',
    region: 'South East',
    county: 'East Sussex',
    lat: 50.8225, lon: -0.1372,
    lastFrostDate: '1 April', lastFrostMonth: 3, lastFrostDay: 1,
    firstFrostDate: '12 November',
    frostFreeDays: 225,
    averageMayLowC: 10,
    description: 'Brighton and the Sussex coast enjoy some of the mildest conditions in the UK, warmed by the English Channel. The sea moderates temperatures throughout the year, reducing frost frequency significantly.',
    plantingAdvice: 'Brighton is one of the best locations in England for early planting. Tender plants can often go outside by late April in sheltered spots. The long frost-free season suits Mediterranean crops like aubergines and basil.',
  },
  {
    slug: 'southampton',
    name: 'Southampton',
    region: 'South East',
    county: 'Hampshire',
    lat: 50.9097, lon: -1.4044,
    lastFrostDate: '8 April', lastFrostMonth: 3, lastFrostDay: 8,
    firstFrostDate: '8 November',
    frostFreeDays: 214,
    averageMayLowC: 9,
    description: 'Southampton\'s position on the Solent gives it a maritime climate with mild winters and early springs. The city is well-sheltered from northerly winds, making it a favourable growing environment.',
    plantingAdvice: 'Southampton gardeners benefit from an early start to the season. Tomatoes and peppers can usually go out from mid-May, with courgettes following shortly after once night temperatures are reliably above 10°C.',
  },
  {
    slug: 'oxford',
    name: 'Oxford',
    region: 'South East',
    county: 'Oxfordshire',
    lat: 51.7520, lon: -1.2577,
    lastFrostDate: '20 April', lastFrostMonth: 3, lastFrostDay: 20,
    firstFrostDate: '26 October',
    frostFreeDays: 189,
    averageMayLowC: 8,
    description: 'Oxford sits in the Thames Valley and can experience cold air pooling on still, clear nights. Despite being in southern England, its inland position and valley topography make it prone to late spring frosts.',
    plantingAdvice: 'Oxford gardeners should wait until early May before planting tender crops outside. The river valleys around Oxford are particularly prone to ground frosts even when air temperatures seem mild.',
    microclimate: 'Cold air drainage in Thames Valley increases frost risk'
  },
  {
    slug: 'cambridge',
    name: 'Cambridge',
    region: 'East of England',
    county: 'Cambridgeshire',
    lat: 52.2053, lon: 0.1218,
    lastFrostDate: '22 April', lastFrostMonth: 3, lastFrostDay: 22,
    firstFrostDate: '22 October',
    frostFreeDays: 183,
    averageMayLowC: 7,
    description: 'Cambridge and the Fens are in one of the driest and coldest regions of England. The flat landscape offers no shelter from cold easterly winds blowing in from continental Europe, and the low-lying terrain is prone to frost pockets.',
    plantingAdvice: 'Cambridge gardeners should be cautious — late frosts are common into late April and occasionally early May. Wait until mid-May before risking tender plants outside.',
    microclimate: 'Exposed to cold easterlies; flat landscape = frost pockets'
  },
  {
    slug: 'norwich',
    name: 'Norwich',
    region: 'East of England',
    county: 'Norfolk',
    lat: 52.6309, lon: 1.2974,
    lastFrostDate: '25 April', lastFrostMonth: 3, lastFrostDay: 25,
    firstFrostDate: '19 October',
    frostFreeDays: 177,
    averageMayLowC: 7,
    description: 'Norfolk\'s position on the east coast exposes it to cold continental air masses in spring. Despite being in the south of England, Norwich regularly sees late frosts due to its low rainfall, clear skies, and flat topography.',
    plantingAdvice: 'Norfolk gardeners should wait until late April or early May before putting tender crops outside. Clear, calm nights in spring mean radiation frosts are common even when daytime temperatures feel warm.',
  },
  // === SOUTH WEST ===
  {
    slug: 'bristol',
    name: 'Bristol',
    region: 'South West',
    county: 'Bristol',
    lat: 51.4545, lon: -2.5879,
    lastFrostDate: '12 April', lastFrostMonth: 3, lastFrostDay: 12,
    firstFrostDate: '31 October',
    frostFreeDays: 202,
    averageMayLowC: 9,
    description: 'Bristol enjoys a mild Atlantic climate, protected from cold easterly winds by the Cotswolds and Mendips. The Avon Gorge creates its own microclimate, and the city\'s elevation varies significantly between neighbourhoods.',
    plantingAdvice: 'Bristol gardeners in lower-lying areas can plant out from mid-May. Those in elevated spots like Clifton should wait an extra week or two, as higher ground sees more overnight frost events.',
  },
  {
    slug: 'exeter',
    name: 'Exeter',
    region: 'South West',
    county: 'Devon',
    lat: 50.7184, lon: -3.5339,
    lastFrostDate: '6 April', lastFrostMonth: 3, lastFrostDay: 6,
    firstFrostDate: '6 November',
    frostFreeDays: 214,
    averageMayLowC: 9,
    description: 'Exeter and Devon benefit from the warming influence of the Gulf Stream. Devon is famous for its mild climate and lush gardens, with frost-free conditions arriving noticeably earlier than in eastern England.',
    plantingAdvice: 'Exeter gardeners are among the luckiest in England. Tender plants can often go outside from late April in sheltered spots. The long growing season suits crops that struggle elsewhere, including outdoor aubergines in warm years.',
  },
  {
    slug: 'penzance',
    name: 'Penzance',
    region: 'South West',
    county: 'Cornwall',
    lat: 50.1186, lon: -5.5372,
    lastFrostDate: '22 March', lastFrostMonth: 2, lastFrostDay: 22,
    firstFrostDate: '25 November',
    frostFreeDays: 248,
    averageMayLowC: 11,
    description: 'Penzance and the far west of Cornwall have the mildest climate in mainland Britain. Surrounded by sea on three sides, temperatures rarely drop below freezing even in winter. The Isles of Scilly, visible on clear days, are even milder.',
    plantingAdvice: 'Cornwall is in a league of its own for UK gardeners. Frost risk effectively ends in late March, and tender plants can go out from mid-April. The very long frost-free season allows crops that are impossible elsewhere in the UK.',
    microclimate: 'Warmest mainland UK climate; Gulf Stream influence'
  },
  {
    slug: 'plymouth',
    name: 'Plymouth',
    region: 'South West',
    county: 'Devon',
    lat: 50.3755, lon: -4.1427,
    lastFrostDate: '2 April', lastFrostMonth: 3, lastFrostDay: 2,
    firstFrostDate: '10 November',
    frostFreeDays: 222,
    averageMayLowC: 10,
    description: 'Plymouth\'s position on the south Devon coast gives it an exceptionally mild maritime climate. The city rarely sees significant frost, and its south-facing slopes provide ideal conditions for tender crops.',
    plantingAdvice: 'Plymouth gardeners enjoy one of England\'s longest growing seasons. Plant out tender crops from late April in sheltered spots, early May for exposed gardens.',
  },
  // === MIDLANDS ===
  {
    slug: 'birmingham',
    name: 'Birmingham',
    region: 'West Midlands',
    lat: 52.4862, lon: -1.8904,
    lastFrostDate: '30 April', lastFrostMonth: 3, lastFrostDay: 30,
    firstFrostDate: '20 October',
    frostFreeDays: 173,
    averageMayLowC: 7,
    description: 'Birmingham and the West Midlands sit at the heart of England, away from the moderating influence of the sea. Springs can be cold and late frosts are common into late April. The elevated areas around the city are particularly frost-prone.',
    plantingAdvice: 'Birmingham gardeners should wait until mid-May before planting tomatoes and peppers outside. The city\'s urban core is slightly warmer than surrounding areas, but suburban gardens in Sutton Coldfield or Solihull should be more cautious.',
  },
  {
    slug: 'coventry',
    name: 'Coventry',
    region: 'West Midlands',
    county: 'West Midlands',
    lat: 52.4068, lon: -1.5197,
    lastFrostDate: '2 May', lastFrostMonth: 4, lastFrostDay: 2,
    firstFrostDate: '17 October',
    frostFreeDays: 168,
    averageMayLowC: 7,
    description: 'Coventry lies in the heart of England and sees a classic Midlands climate — warm summers but cold, frosty springs. Being inland and at moderate elevation, it\'s exposed to cold air from any direction.',
    plantingAdvice: 'Coventry gardeners should be patient — May frosts are not unusual. Wait until mid-May before planting frost-tender crops outside, and keep fleece handy for cold snaps.',
  },
  {
    slug: 'nottingham',
    name: 'Nottingham',
    region: 'East Midlands',
    county: 'Nottinghamshire',
    lat: 52.9548, lon: -1.1581,
    lastFrostDate: '28 April', lastFrostMonth: 3, lastFrostDay: 28,
    firstFrostDate: '20 October',
    frostFreeDays: 175,
    averageMayLowC: 7,
    description: 'Nottingham sits in the Trent Valley, which can channel cold air on clear nights. The city has a classic East Midlands climate — relatively dry with cold springs compared to western England.',
    plantingAdvice: 'Nottingham gardeners should aim for mid-May for tender crops. The Trent Valley is prone to frost pockets, so gardeners in low-lying areas near the river should be especially cautious.',
  },
  {
    slug: 'leicester',
    name: 'Leicester',
    region: 'East Midlands',
    county: 'Leicestershire',
    lat: 52.6369, lon: -1.1398,
    lastFrostDate: '30 April', lastFrostMonth: 3, lastFrostDay: 30,
    firstFrostDate: '18 October',
    frostFreeDays: 171,
    averageMayLowC: 7,
    description: 'Leicester is a typical Midlands city with cold winters and unpredictable springs. Its inland position means it lacks the moderating influence of the sea and can experience sudden late frosts in May.',
    plantingAdvice: 'Mid-May is the safe target for tender plants in Leicester. Keep an eye on the 14-day forecast throughout May as late cold snaps can occur.',
  },
  {
    slug: 'shrewsbury',
    name: 'Shrewsbury',
    region: 'West Midlands',
    county: 'Shropshire',
    lat: 52.7082, lon: -2.7540,
    lastFrostDate: '5 May', lastFrostMonth: 4, lastFrostDay: 5,
    firstFrostDate: '15 October',
    frostFreeDays: 163,
    averageMayLowC: 6,
    description: 'Shrewsbury sits in a meander of the River Severn, and this low-lying position makes it very prone to frost. The surrounding Shropshire hills can trap cold air in the valley, and late frosts in May are not uncommon.',
    plantingAdvice: 'Shrewsbury gardeners should be among the most cautious in England. Don\'t rush tender plants outside before mid-May, and watch forecasts carefully. The valley bottom locations are particularly vulnerable to late frosts.',
    microclimate: 'River valley position = significant cold air drainage risk'
  },
  // === NORTH WEST ===
  {
    slug: 'manchester',
    name: 'Manchester',
    region: 'North West',
    lat: 53.4808, lon: -2.2426,
    lastFrostDate: '10 May', lastFrostMonth: 4, lastFrostDay: 10,
    firstFrostDate: '10 October',
    frostFreeDays: 153,
    averageMayLowC: 6,
    description: 'Manchester has a famously wet, cool climate driven by Atlantic weather systems. While it rarely gets extreme frosts, springs are cool and slow to warm. The surrounding Pennines and hills mean temperatures drop quickly outside the city centre.',
    plantingAdvice: 'Manchester gardeners should wait until mid-May for tender crops. The city centre is slightly warmer than outlying areas — gardeners in Didsbury, Sale, or Altrincham should add a week of caution.',
  },
  {
    slug: 'liverpool',
    name: 'Liverpool',
    region: 'North West',
    county: 'Merseyside',
    lat: 53.4084, lon: -2.9916,
    lastFrostDate: '5 May', lastFrostMonth: 4, lastFrostDay: 5,
    firstFrostDate: '13 October',
    frostFreeDays: 161,
    averageMayLowC: 7,
    description: 'Liverpool\'s position on the Irish Sea coast gives it a milder maritime climate than inland northern cities. The sea keeps temperatures relatively stable, but springs are still cool by southern standards.',
    plantingAdvice: 'Liverpool gardeners benefit from the coastal influence. Early May is usually safe for tender crops in sheltered spots, though mid-May is the safer bet for exposed gardens.',
  },
  {
    slug: 'chester',
    name: 'Chester',
    region: 'North West',
    county: 'Cheshire',
    lat: 53.1905, lon: -2.8910,
    lastFrostDate: '5 May', lastFrostMonth: 4, lastFrostDay: 5,
    firstFrostDate: '14 October',
    frostFreeDays: 162,
    averageMayLowC: 7,
    description: 'Chester sits in the Cheshire Plain, which benefits from some shelter from the Welsh mountains to the west. The Dee Valley can experience cold air pooling but the city generally has a mild northwest climate.',
    plantingAdvice: 'Chester gardeners can usually plant tender crops in early-to-mid May. The Dee Valley bottom is more frost-prone, so elevated garden positions are safer for early planting.',
  },
  // === YORKSHIRE ===
  {
    slug: 'leeds',
    name: 'Leeds',
    region: 'Yorkshire',
    county: 'West Yorkshire',
    lat: 53.8008, lon: -1.5491,
    lastFrostDate: '14 May', lastFrostMonth: 4, lastFrostDay: 14,
    firstFrostDate: '8 October',
    frostFreeDays: 147,
    averageMayLowC: 6,
    description: 'Leeds sits at the eastern edge of the Pennines and experiences a typical Yorkshire climate — cool and unpredictable in spring. The Aire Valley can channel cold air, and late frosts are common into May.',
    plantingAdvice: 'Leeds gardeners should wait until mid-to-late May for tender crops. The temperature difference between the city centre and suburban areas can be significant — gardeners in Otley or Wetherby face more frost risk than those in the city.',
  },
  {
    slug: 'sheffield',
    name: 'Sheffield',
    region: 'Yorkshire',
    county: 'South Yorkshire',
    lat: 53.3811, lon: -1.4701,
    lastFrostDate: '12 May', lastFrostMonth: 4, lastFrostDay: 12,
    firstFrostDate: '9 October',
    frostFreeDays: 150,
    averageMayLowC: 6,
    description: 'Sheffield is famously hilly, and elevation plays a huge role in when frost risk passes. The city centre at lower elevations warms earlier than the western suburbs heading into the Peak District.',
    plantingAdvice: 'Sheffield gardeners need to factor in elevation. City centre and eastern suburbs can plant out by mid-May. Western areas towards the Peak District should wait until late May — frosts at 200m+ are possible well into May.',
    microclimate: 'Large elevation variation across city — up to 250m difference'
  },
  {
    slug: 'york',
    name: 'York',
    region: 'Yorkshire',
    county: 'North Yorkshire',
    lat: 53.9600, lon: -1.0873,
    lastFrostDate: '10 May', lastFrostMonth: 4, lastFrostDay: 10,
    firstFrostDate: '11 October',
    frostFreeDays: 154,
    averageMayLowC: 6,
    description: 'York sits in the Vale of York, a flat lowland corridor that can channel cold Arctic air southward. The city has a colder, drier climate than western Yorkshire and experiences more severe spring frosts.',
    plantingAdvice: 'York gardeners should wait until mid-May. The flat Vale of York is particularly prone to radiation frosts on calm, clear nights — always check the overnight forecast before planting tender crops.',
  },
  {
    slug: 'hull',
    name: 'Hull',
    region: 'Yorkshire',
    county: 'East Yorkshire',
    lat: 53.7457, lon: -0.3367,
    lastFrostDate: '8 May', lastFrostMonth: 4, lastFrostDay: 8,
    firstFrostDate: '14 October',
    frostFreeDays: 159,
    averageMayLowC: 7,
    description: 'Hull\'s position on the Humber Estuary gives it some maritime influence, but cold North Sea air means springs can be chilly. The flat Holderness Plain offers no shelter from cold easterly and northerly winds.',
    plantingAdvice: 'Hull gardeners should target mid-May for tender crops. East-facing gardens are particularly exposed to cold sea breezes — west or south-facing aspects can plant slightly earlier.',
  },
  // === NORTH EAST ===
  {
    slug: 'newcastle',
    name: 'Newcastle',
    region: 'North East',
    county: 'Tyne and Wear',
    lat: 54.9783, lon: -1.6178,
    lastFrostDate: '18 May', lastFrostMonth: 4, lastFrostDay: 18,
    firstFrostDate: '3 October',
    frostFreeDays: 138,
    averageMayLowC: 6,
    description: 'Newcastle and Tyneside experience a cool, maritime climate with cold springs. Cold North Sea air keeps temperatures low into May, and frosts can occur well into spring. The Tyne Valley provides some shelter but the coast is fully exposed.',
    plantingAdvice: 'Newcastle gardeners should wait until late May before planting tender crops outside. The short growing season means choosing fast-maturing varieties of tomatoes and peppers is wise.',
  },
  {
    slug: 'sunderland',
    name: 'Sunderland',
    region: 'North East',
    county: 'Tyne and Wear',
    lat: 54.9069, lon: -1.3838,
    lastFrostDate: '20 May', lastFrostMonth: 4, lastFrostDay: 20,
    firstFrostDate: '2 October',
    frostFreeDays: 135,
    averageMayLowC: 6,
    description: 'Sunderland sits directly on the North Sea coast and experiences cold, raw springs. Sea frets can keep temperatures low even in May and June, making it one of the more challenging climates for tender crops in England.',
    plantingAdvice: 'Sunderland gardeners face one of the shorter growing seasons in England. Late May is the sensible target for tender crops. Cloches and polytunnels are worth considering for reliable results.',
  },
  {
    slug: 'durham',
    name: 'Durham',
    region: 'North East',
    county: 'County Durham',
    lat: 54.7753, lon: -1.5849,
    lastFrostDate: '16 May', lastFrostMonth: 4, lastFrostDay: 16,
    firstFrostDate: '5 October',
    frostFreeDays: 142,
    averageMayLowC: 6,
    description: 'Durham sits on a peninsula above the River Wear, giving it some elevation. The county is diverse — from the industrial coast to the high Pennines — but the city itself has a typical cool northern climate with late springs.',
    plantingAdvice: 'Durham gardeners should target late May for tender crops. Choose compact, early-fruiting varieties to make the most of the shorter growing season.',
  },
  // === NORTH WEST (CONTINUED) ===
  {
    slug: 'carlisle',
    name: 'Carlisle',
    region: 'North West',
    county: 'Cumbria',
    lat: 54.8951, lon: -2.9382,
    lastFrostDate: '22 May', lastFrostMonth: 4, lastFrostDay: 22,
    firstFrostDate: '28 September',
    frostFreeDays: 129,
    averageMayLowC: 5,
    description: 'Carlisle sits in the Eden Valley near the Scottish border and experiences one of England\'s shorter growing seasons. Cold northerly airflows from Scotland and proximity to the Pennines and Lake District fells means late frosts are common.',
    plantingAdvice: 'Carlisle gardeners have a challenging climate for tender crops. Late May or early June is the safe window. Raised beds help warm the soil, and fleece protection is advisable for weeks after planting out.',
  },
  // === WALES ===
  {
    slug: 'cardiff',
    name: 'Cardiff',
    region: 'Wales',
    county: 'South Glamorgan',
    lat: 51.4816, lon: -3.1791,
    lastFrostDate: '15 April', lastFrostMonth: 3, lastFrostDay: 15,
    firstFrostDate: '31 October',
    frostFreeDays: 199,
    averageMayLowC: 8,
    description: 'Cardiff benefits from its coastal position on the Bristol Channel, with mild Atlantic air keeping frosts relatively rare. The Vale of Glamorgan to the west is particularly mild, though the mountains to the north bring colder air in spring.',
    plantingAdvice: 'Cardiff gardeners can plant tender crops from early-to-mid May. South-facing gardens near the coast can push this earlier. Gardens in the valleys heading north into the Brecon Beacons should be more cautious.',
  },
  {
    slug: 'swansea',
    name: 'Swansea',
    region: 'Wales',
    county: 'West Glamorgan',
    lat: 51.6214, lon: -3.9436,
    lastFrostDate: '12 April', lastFrostMonth: 3, lastFrostDay: 12,
    firstFrostDate: '4 November',
    frostFreeDays: 206,
    averageMayLowC: 9,
    description: 'Swansea sits on a south-facing bay and is one of the mildest cities in Wales. The Gower Peninsula, just to the west, has a famously mild microclimate. Atlantic air keeps frosts rare and springs arrive relatively early.',
    plantingAdvice: 'Swansea and Gower gardeners enjoy mild conditions. Tender crops can go out from early May in most gardens. The Gower coast particularly benefits from the sea\'s moderating influence.',
  },
  // === SCOTLAND ===
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    region: 'Scotland',
    county: 'Lothian',
    lat: 55.9533, lon: -3.1883,
    lastFrostDate: '28 May', lastFrostMonth: 4, lastFrostDay: 28,
    firstFrostDate: '19 September',
    frostFreeDays: 114,
    averageMayLowC: 5,
    description: 'Edinburgh has a notoriously cold, windy climate. The east coast position exposes the city to cold North Sea air, and the surrounding hills channel wind. Cold springs mean frost risk persists well into late May.',
    plantingAdvice: 'Edinburgh gardeners face a real challenge with tender crops. June is the realistic safe window for tomatoes and peppers outside — or use a greenhouse. Raised beds, south-facing walls, and fleece are essential tools.',
  },
  {
    slug: 'glasgow',
    name: 'Glasgow',
    region: 'Scotland',
    county: 'Strathclyde',
    lat: 55.8642, lon: -4.2518,
    lastFrostDate: '26 May', lastFrostMonth: 4, lastFrostDay: 26,
    firstFrostDate: '23 September',
    frostFreeDays: 120,
    averageMayLowC: 5,
    description: 'Glasgow\'s west coast position gives it a wetter, slightly milder climate than Edinburgh, but it still has a short growing season. The Clyde Valley has some sheltered spots that can push last frost dates earlier.',
    plantingAdvice: 'Glasgow gardeners should target June for tender crops outside. The Clyde Valley microclimate is notably warmer than surrounding areas — gardeners there can be slightly more ambitious. Polytunnels are popular and effective here.',
  },
  {
    slug: 'aberdeen',
    name: 'Aberdeen',
    region: 'Scotland',
    county: 'Aberdeenshire',
    lat: 57.1497, lon: -2.0943,
    lastFrostDate: '10 June', lastFrostMonth: 5, lastFrostDay: 10,
    firstFrostDate: '10 September',
    frostFreeDays: 92,
    averageMayLowC: 4,
    description: 'Aberdeen has one of the most challenging climates in the UK for gardening. The cold North Sea keeps temperatures low even in summer, and frost risk extends well into June in most years. The short growing season demands careful variety selection.',
    plantingAdvice: 'Aberdeen gardeners should plan around a very short outdoor season. Tender crops outside before June carry significant frost risk. A polytunnel or greenhouse is strongly recommended for reliable results with tomatoes and peppers.',
    microclimate: 'Cold North Sea influence; one of UK\'s shortest growing seasons'
  },
  {
    slug: 'inverness',
    name: 'Inverness',
    region: 'Scotland',
    county: 'Highland',
    lat: 57.4778, lon: -4.2247,
    lastFrostDate: '15 June', lastFrostMonth: 5, lastFrostDay: 15,
    firstFrostDate: '5 September',
    frostFreeDays: 82,
    averageMayLowC: 4,
    description: 'Inverness and the Scottish Highlands have the most challenging gardening climate in the UK. Frost can occur in any month of the year at higher elevations, and even the city itself has a very short frost-free window.',
    plantingAdvice: 'Inverness gardeners should not attempt tender crops outside before mid-June. Even then, keep fleece close. Greenhouses and polytunnels are not just useful here — they\'re almost essential for any reliable cropping.',
    microclimate: 'Highland climate; frost possible in any month at elevation'
  },
  // === NORTHERN IRELAND ===
  {
    slug: 'belfast',
    name: 'Belfast',
    region: 'Northern Ireland',
    county: 'County Antrim',
    lat: 54.5973, lon: -5.9301,
    lastFrostDate: '18 May', lastFrostMonth: 4, lastFrostDay: 18,
    firstFrostDate: '2 October',
    frostFreeDays: 137,
    averageMayLowC: 6,
    description: 'Belfast has a classic Atlantic climate — mild and wet. The surrounding hills and the lough provide some shelter, but cool temperatures and late springs are typical. The city centre benefits slightly from urban warming.',
    plantingAdvice: 'Belfast gardeners should target late May for tender crops. The cool, moist climate is great for brassicas and salads but challenging for heat-loving crops like tomatoes. Outdoor crops benefit from a sheltered, south-facing position.',
  },
  // === MORE ENGLISH LOCATIONS ===
  {
    slug: 'portsmouth',
    name: 'Portsmouth',
    region: 'South East',
    county: 'Hampshire',
    lat: 50.8198, lon: -1.0880,
    lastFrostDate: '2 April', lastFrostMonth: 3, lastFrostDay: 2,
    firstFrostDate: '10 November',
    frostFreeDays: 222,
    averageMayLowC: 10,
    description: 'Portsmouth and Southsea sit on a low-lying island almost entirely surrounded by sea. This maritime location gives it one of the warmest and most frost-free climates in northern Europe, comparable to coastal Brittany.',
    plantingAdvice: 'Portsmouth gardeners enjoy exceptional conditions. Tender crops can go out from late April in most years. The island location means truly dramatic frosts are rare — though still check forecasts before planting.',
  },
  {
    slug: 'reading',
    name: 'Reading',
    region: 'South East',
    county: 'Berkshire',
    lat: 51.4543, lon: -0.9781,
    lastFrostDate: '18 April', lastFrostMonth: 3, lastFrostDay: 18,
    firstFrostDate: '29 October',
    frostFreeDays: 194,
    averageMayLowC: 8,
    description: 'Reading sits in the Thames Valley between the Chilterns and the North Downs. The valley position can cause cold air to pool on clear nights, making frost dates later than the latitude alone would suggest.',
    plantingAdvice: 'Reading gardeners should aim for early-to-mid May for tender crops. Gardens in the Thames flood plain are particularly susceptible to late frosts due to cold air drainage.',
  },
  {
    slug: 'stoke-on-trent',
    name: 'Stoke-on-Trent',
    region: 'West Midlands',
    county: 'Staffordshire',
    lat: 53.0027, lon: -2.1794,
    lastFrostDate: '5 May', lastFrostMonth: 4, lastFrostDay: 5,
    firstFrostDate: '14 October',
    frostFreeDays: 162,
    averageMayLowC: 7,
    description: 'Stoke-on-Trent sits at the southern end of the Pennines at moderate elevation. The Potteries have a cool climate and springs are slow to warm. Elevation varies significantly across the area, affecting local frost dates.',
    plantingAdvice: 'Stoke gardeners should target mid-May for tender crops. Higher areas towards the Staffordshire Moorlands can see frosts well into May — check local elevation before deciding when to plant out.',
  },
  {
    slug: 'derby',
    name: 'Derby',
    region: 'East Midlands',
    county: 'Derbyshire',
    lat: 52.9225, lon: -1.4746,
    lastFrostDate: '30 April', lastFrostMonth: 3, lastFrostDay: 30,
    firstFrostDate: '18 October',
    frostFreeDays: 171,
    averageMayLowC: 7,
    description: 'Derby lies at the gateway to the Peak District, and its climate is influenced by proximity to the Pennines. The Derwent Valley can channel cold air, though the city itself is well-sheltered compared to the high ground to the north.',
    plantingAdvice: 'Derby gardeners should target mid-May for tender crops. Those in northern suburbs closer to the Peak District, or with gardens in the Derwent Valley, should add a week of caution.',
  },
  {
    slug: 'lincoln',
    name: 'Lincoln',
    region: 'East Midlands',
    county: 'Lincolnshire',
    lat: 53.2307, lon: -0.5406,
    lastFrostDate: '25 April', lastFrostMonth: 3, lastFrostDay: 25,
    firstFrostDate: '21 October',
    frostFreeDays: 179,
    averageMayLowC: 7,
    description: 'Lincoln is divided by the limestone ridge of the Lincoln Edge. The lower city (Witham valley) is prone to cold air pooling, while the upper city on the ridge benefits from better air drainage and slightly earlier frost-free conditions.',
    plantingAdvice: 'Lincoln gardeners in the lower city should be more cautious about late frosts. Early-to-mid May is the target. Those on the ridge can sometimes plant a week earlier.',
  },
  {
    slug: 'peterborough',
    name: 'Peterborough',
    region: 'East of England',
    county: 'Cambridgeshire',
    lat: 52.5736, lon: -0.2406,
    lastFrostDate: '22 April', lastFrostMonth: 3, lastFrostDay: 22,
    firstFrostDate: '22 October',
    frostFreeDays: 183,
    averageMayLowC: 7,
    description: 'Peterborough sits on the edge of the Fens, one of the coldest regions in England. The flat, drained fenland around the city offers no shelter from cold easterly winds, and clear nights lead to significant radiation frosts.',
    plantingAdvice: 'Peterborough gardeners should be cautious — the Fens are notorious for late frosts. Late April is the earliest safe window, early May is more reliable for tender crops.',
  },
  {
    slug: 'ipswich',
    name: 'Ipswich',
    region: 'East of England',
    county: 'Suffolk',
    lat: 52.0567, lon: 1.1482,
    lastFrostDate: '20 April', lastFrostMonth: 3, lastFrostDay: 20,
    firstFrostDate: '25 October',
    frostFreeDays: 188,
    averageMayLowC: 8,
    description: 'Ipswich has a typical East Anglian climate — dry and cool. Cold North Sea air can bring late frosts, but the Orwell estuary provides some local moderation. Ipswich is drier than western towns of similar latitude.',
    plantingAdvice: 'Ipswich gardeners should aim for early-to-mid May for tender crops. The dry climate is excellent for disease-prone crops like tomatoes once established outside.',
  },
]

// Helper to get location by slug
export function getLocationBySlug(slug: string): UKLocation | undefined {
  return ukLocations.find(l => l.slug === slug)
}

// All slugs for static generation
export function getAllLocationSlugs(): string[] {
  return ukLocations.map(l => l.slug)
}

// Group by region
export function getLocationsByRegion(): Record<string, UKLocation[]> {
  return ukLocations.reduce((acc, loc) => {
    if (!acc[loc.region]) acc[loc.region] = []
    acc[loc.region].push(loc)
    return acc
  }, {} as Record<string, UKLocation[]>)
}
